# Generated by Django 5.0.3 on 2024-04-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='About text'),
        ),
        migrations.AlterField(
            model_name='home',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono de contacto'),
        ),
    ]
